### PR TITLE
:bug: Fix Revolut parser

### LINKED ISSUE #269: Revolut parser not working
**Describe the bug**
Trying to map an export from the Revolut app results in the following error:
> The file Revolut-BGN-Statement-1 Feb 2018 to 25 Mar 2020.csv errored: No parser is available for this file.

**To Reproduce**
1. Export a statement from the Revolut app
2. Drop it at https://ynap.leolabs.org/

**Expected behavior**
The Revolut statement is successfully converted to YANB import file.

**Actual behavior**
The following error is rendered:
> The file Revolut-BGN-Statement-1 Feb 2018 to 25 Mar 2020.csv errored: No parser is available for this file.

**Desktop:**
 - OS: macOS Catalina 10.15.3
 - Browser: Google Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Smartphone:**
 - Device: iPhone XS Max
 - OS: iOS 13.3.1
 - App: Revolut 6.32.1 (Latest)

**Additional context**
I have noticed the following things while looking at the Revolut parser spec:
* The CSV format differs as follows:
  * Expected (Parser/Spec):
```
Completed Date ; Description ; Paid Out (RON) ; Paid In (RON) ; Exchange Out; Exchange In; Balance (RON); Category; Notes
```
  * Actual (as exported by the latest Revolut app version)
```
Completed Date ; Reference ; Paid Out (RON) ; Paid In (RON) ; Exchange Out ; Exchange In ; Balance (BGN) ; Exchange Rate ; Category
```
* The CSV filename pattern has changed:
  * Expected (Parser/Spec):
```
Revolut-RON-Statement-May 2018 – Apr 2019.csv
```
  * Actual (as exported by the latest Revolut app version)
```
Revolut-BGN-Statement-1 Feb 2018 to 25 Mar 2020.csv
```
* The `Completed Date` column does not contain year for transactions made within the current year. For transactions made in past years (e.g. 2019), it's present.

### PR DESCRIPTION
**Pull request by marchev**
Fixes #269

### CODE REVIEW

**Comment by marchev** [comment]
Hi @leolabs! Not sure why the code coverage includes a couple of other commits along with my PR -> `fcbe296...62d250b` I believe this is a mistake and something which leads to decreased code coverage for this PR but that's up to you really 🙂

**Comment by leolabs** [comment]
Thanks for your PR!

There are two things I'd like to resolve before merging it. 

1. It might be nice for YNAP to support both the new and the old file formats. If the difference in the data structure isn't too big, maybe supporting both would be relatively easy to implement.
2. When generating date strings, YNAP adheres to YNAB's [CSV examples](https://docs.youneedabudget.com/article/921-formatting-csv-file). Their date format is MM/DD/YY. Could you make sure that the dates in your PR's output are formatted correctly?

**Comment by marchev** [comment]
> 1. It might be nice for YNAP to support both the new and the old file formats. If the difference in the data structure isn't too big, maybe supporting both would be relatively easy to implement.

Will check and see if I could implement both of those.

> 2. When generating date strings, YNAP adheres to YNAB's [CSV examples](https://docs.youneedabudget.com/article/921-formatting-csv-file). Their date format is MM/DD/YY. Could you make sure that the dates in your PR's output are formatted correctly?

I decided to change the format to ISO 8601 date as it's less ambiguous. While the other format had issues in my locale, the ISO 8601 seem to be working just fine and supported by YNAB. It's your project in the end so please let me know which way you prefer those to be, happy for me to change it.

image

**Comment by leolabs** [comment]
Regarding the second point, it's good to know that YNAB supports ISO 8601. I prefer that format as well, so maybe I'll convert all parsers to use that format in the future. You can just leave your parser as-is and I'll take care of the others then :)

**Pull request merged**
